"""empty message

Revision ID: acf76a5f05ef
Revises: dc12df518aef
Create Date: 2021-09-15 18:51:49.317516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acf76a5f05ef'
down_revision = 'dc12df518aef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('city_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'city', ['city_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'city_id')
    # ### end Alembic commands ###
